data_analytic/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'data_analytic.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^demo/', include('data_analytic.demo_urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('data_analytic.views',
    # Report Creation:
    url(r'^$','dashboard'),
    url(r'^chart/(\d+)/$','show_chart'),
    url(r'^reports/$','reports'),
    url(r'^dashboard/$','dashboard'),
    
    url(r'^getDimensionsAndMetrics/(?P<datasourceId>.+)$', 'getDimensionsAndMetrics'),
    #url(r'^viewreport/(?P<reportId>.+)/(?P<reportType>.+)/$', 'viewReport'),
    url(r'^dashboard/$', 'dashboard'),
    url(r'^exploredata/$', 'explore_data'),
    url(r'^exploredata/(\d+)/$', 'explore_data'),
    url(r'^exploredata/(?P<source_id>\d)/(?P<fdate>\d{4}-\d{2}-\d{2})/(?P<tdate>\d{4}-\d{2}-\d{2})$','explore_data'),
    url(r'^heatmap/$', 'heatmap'),
    url(r'^getHeatMap/(?P<geoId>.+)/(?P<startDate>\d{4}-\d{2}-\d{2})/(?P<endDate>\d{4}-\d{2}-\d{2})/$', 'getHeatMap'),

    # login url details
    url(r'^accounts/login/$', 'login'),
    url(r'^accounts/logout/$', 'logout'),
    url(r'^accounts/settings/$', 'usersettings'),
    url(r'^accounts/changepassword/$', 'changepassword'),

    url(r'^accounts/userreportslist/$', 'userreports'),
    
    url(r'^accounts/reports/(?P<action>.+)/(?P<reportId>.+)/$', 'userreportdetails'),
    url(r'^accounts/reports/(?P<action>.+)/$', 'userreportdetails'),

    # Add to Dashboard url
    url(r'^addDashboard/(\d+)/$', 'addDashboard'),
    url(r'^removeDashboard/(\d+)/$', 'removeDashboard'),
)

data_analytic/forms.py
from django import forms
import re

from data_analytic.models import ReportInfo, DataSource

class LoginForm(forms.Form):
    username = forms.CharField(label=("Username"), max_length=30)
    password = forms.CharField(label=("Password"), widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):        
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})

    def clean_username(self):
        username = self.cleaned_data['username']
        if  re.match(r'^[\W\d]*$', username):
            raise forms.ValidationError("Enter a valid username.")
        return username

    def clean_password(self):
        password = self.cleaned_data['password']
        if  re.match(r'^[\s]*$', password):
            raise forms.ValidationError("Enter a valid password.")
        return password
    

class ReportForm(forms.Form):
    
    reportInfoObj = ReportInfo()
    CHART_TYPE_CHOICES = reportInfoObj.CHART_TYPE_CHOICE
    DATASOURCE_CHOICES = DataSource.objects.values_list('id', 'name')
    FILTER_CHOICES = (('date','Date'), ('month','metrics'))

    name = forms.CharField(label=("Report Name"), max_length=30, required=True)
    description = forms.CharField(label=("Description"), max_length=30, required=False)
    datasource = forms.ChoiceField(label=("DataSource"), choices=DATASOURCE_CHOICES, required=True)
    chart_type = forms.ChoiceField(label=("Chart Type"), choices=CHART_TYPE_CHOICES, required=True)
    height = forms.CharField(label=("Height"), max_length=5, required=True)
    width = forms.CharField(label=("Width"), max_length=5, required=True)
    is_chart = forms.BooleanField(label=("Is Chart"), required=False)
    is_tabular = forms.BooleanField(label=("Is Tabular"), required=False)
    is_filter = forms.BooleanField(label=("Is Filter"), required=False)
    filter_column = forms.ChoiceField(label=("Filter Column"), choices=FILTER_CHOICES, required=False)


    def __init__(self, *args, **kwargs):        
        super(ReportForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'CommonField TextBox'})
        self.fields['description'].widget.attrs.update({'class': 'CommonField TextBox'})
        self.fields['datasource'].widget.attrs.update({'class': 'CommonField TextBox'})        
        self.fields['chart_type'].widget.attrs.update({'class': 'CommonField'})
        self.fields['height'].widget.attrs.update({'class': 'CommonField TextBox'})
        self.fields['width'].widget.attrs.update({'class': 'CommonField TextBox'})
        self.fields['is_chart'].widget.attrs.update({'class': 'CommonField TextBox'})
        self.fields['is_tabular'].widget.attrs.update({'class': 'CommonField TextBox'})        
        self.fields['is_filter'].widget.attrs.update({'class': 'CommonField TextBox'})        
        self.fields['filter_column'].widget.attrs.update({'class': 'CommonField'})        

        if not self.fields['chart_type'].choices[0][0] == '':
            self.fields['chart_type'].choices.insert(0, ('', '--------- Select Chart Type ---------' ) )
        
        if not self.fields['datasource'].choices[0][0] == '':
            self.fields['datasource'].choices.insert(0, ('', '--------- Select Datasource ---------' ) )

templates/base.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
		{% load media_tags %}
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="keywords" content="" />
        <link rel="icon" href="favicon.ico" />
        <title>TigmaAnalytics : {{ page_title }}</title>
        <link rel="stylesheet" href='{% media_path "css/jquery-ui_smoothness.css" %}' />
		<link rel="stylesheet" href='{% media_path "css/normalize.css" %}' />
        <link rel="stylesheet" href='{% media_path "css/style.css" %}' />        
		<link type="text/css" rel="stylesheet" href='{% media_path "css/responsive.css" %}' media="screen">

        {% block css_media %}
        {% endblock %}

        {% block load_nvd3_chart_jscss %}
        {% endblock %}

    </head>
	<body>
		<div class="Wrapper">
			<header class="header">
				<section class="navbar-header"> 
					<a href="{% virtual_path %}/" title="TigmaAnalitics" class="Logo"> 
						<img src='{% media_path "images/logo.png" %}' alt="Logo.png" class="logo-img"> 
					</a> 
				</section>
				<nav class="Navigation">
					<ul class="SideBar-DropDown">
						<li {% if page_title == "Reports" %} class="Active" {% endif %}>
							<a href="{% virtual_path %}/reports/" title="Reports"><span class="Icon-SideBar-DropDown Icon-Entities"></span>Reports</a></li>
						<li {% if page_title == "Dashboard" %} class="Active" {% endif %}>
							<a href="{% virtual_path %}/dashboard/" title="Dashboard"><span class="Icon-SideBar-DropDown Icon-Dashboard"></span>Dashboard</a></li>
						<li {% if page_title == "ExploreData" %} class="Active" {% endif %}>
							<a href="{% virtual_path %}/exploredata/" title="Explore"><span class="Icon-SideBar-DropDown Icon-Explore"></span>Explore</a></li>
						<li {% if page_title == "Heatmap" %} class="Active" {% endif %}>
							<a href="{% virtual_path %}/heatmap/" title="Heat Map"><span class="Icon-SideBar-DropDown Icon-Apps"></span>Heat Map</a></li>
					</ul>
				</nav>
				<div class="Admin-Heading">
					<ul class="Admin-Header">
						<li>
							<span class="Admin-UserName">{{ user.username }}</span>
							<div class="Admin-Submenu-Conatiner dropdown"> <span class="Admin-SubMenu-Arrow"></span>
								<ul class="Admin-SubMenu">
									<li class="Admin-UserName">{{ user.username }}</li>
									<li><a href="#">Profile</a></li>
									<li><a href="#">Change Password</a></li>
									<li><a href="#">Recent Status</a></li>
									<li><a href="{% virtual_path %}/accounts/logout/">Logout</a></li>
								</ul>
							</div>
						</li>
						<li>
							<a href="{% virtual_path %}/accounts/settings/" title="IconSettinb">
								<img src='{% media_path "images/Icon-Setting.png" %}' alt="Icon-Setting.png"></a>
						</li>
					</ul>
				</div>
			</header>
			<div class="Content-" style="width:100%; float:left; margin-top:-0px; position:relative">
				<aside class="SideBar" {% if page_title == "Dashboard" or page_title == "Heatmap" or page_title == "Changepassword" %} style="display:none;" {% endif %}>
					<div class="Nav-SearchBox-Container"> 
						<span class="SideBar-Title Hide-Collapse">{{ page_title }}</span> 
						<span  class="Search-Button"></span> <span class="Button-toggle"></span> 
					</div>
					<div class="SideBar-Form-Group sideBar-Space">
						<input type="text" class="SideBar-TextBox" placeholder="Search...">
					</div>
					<div class="SideaBar-Navigation">
						{% block side_menu %}
						
						{% endblock %}
					</div>
				</aside>
				<div class="Content-Wrapper">
					<div class="Content-Box">
						<input id="hdnvirtualpath" type="hidden" value='{% virtual_path %}' />
						{% block content %}
						
						{% endblock %}
					</div>
				</div>
			</div>
		</div>
	</body>		

	<!-- java script region  -->
	<script src='{% media_path "js/jquery-1.11.1.min.js" %}'></script>
	<script src='{% media_path "js/jquery-1.11.0_ui.js" %}'></script>
	<script src='{% media_path "js/dataanalytic.js" %}'></script>
	<script src='{% media_path "js/html5.js" %}'></script>	
	{% block script_media %}
	{% endblock %}
</html>

templates/changepassword.html
{% extends "base.html" %}
{% load media_tags %}

{% block css_media %}
<style>
    #form-3 label{
        display: -moz-grid-group;
        width: 100px;
        text-align: right
    }
    #form-3_submit{
        padding-left: 100px;
    }
    #form-3 div{
        margin-top: 0em;
    }

    .messagelist {
        clear: both;
        color: #CC0000;
        display: none;
        font-size: 80%;
        padding: 3px 0 0 5px;
        width: 308px;
    }

</style>
{% endblock %}

{% block side_menu %}
	<ul class="Sidebar-Navi-Descrpition">
		<li>
			<a href="{% virtual_path %}/accounts/userreportslist/" title="Reports">
				<span class="Circle color-lightblue"></span>
				<span class="Hide-Collapse">Reports</span>
			</a>
		</li>
		<li>
			<a href="#" title="Profile">
				<span class="Circle color-red"></span>
				<span class="Hide-Collapse">Profile</span>
			</a>
		</li>
		<li class="Active">
			<a href="{% virtual_path %}/accounts/changepassword/" title="Change Password">
				<span class="Circle color-orange"></span>
				<span class="Hide-Collapse">Change Password</span>
			</a>
		</li>
		<li>
			<a href="#" title="Recent Status">
				<span class="Circle color-lightgreen"></span>
				<span class="Hide-Collapse">Recent Status</span>
			</a>
		</li>
		<li>
			<a href="#" title="Logout">
				<span class="Circle color-green"></span>
				<span class="Hide-Collapse">Logout</span>
			</a>
		</li>		
	</ul>
{% endblock %}

{% block content %}
	<div id="main-content-liquid" style="width:70%; margin: 0px 0px 0px 0px;">
        <h1 id="rdlTitle" class="h1">{{ page_title }}</h1>
        <form id="form-3" action="." method="POST"> {% csrf_token %}
			<div class="messagelist" id="message" style="text-align:center">
				{% if message != '' %}
					<p>{{ message }}</p>
				{% endif %}
			</div>
            <table id="tblChart" cellspacing="0" cellpadding="0" border="0">
                <tr>
                    <td align="center" valign="middle">
                        <label id="lblNewPswd" for="txtNewPswd">New Password </label>
					</td>
                    <td style="width:5px"></td>
                    <td align="center" valign="middle">
                        <input id="txtNewPswd" style="height: 25px; border:0.25px solid" type="password" name="txtNewPswd" />
					</td>
                    <td>
                        <span id="requiredNewPass" class="error"></span>
					</td>
                </tr>
                <tr>
                    <td align="center" valign="middle">
                        <label id="lblConfirmPswd" for="txtConfirmPswd">Confirm Password </label>
					</td>
                    <td style="width:5px"></td>
                    <td align="center" valign="middle">
                        <input id="txtConfirmPswd" style="height: 25px; border:0.25px solid" type="password" name="txtConfirmPswd" />
					</td>
                    <td>
                        <span id="requiredConfirmPass" class="error"></span>
					</td>
                </tr>
                <tr>
					<td style="width:5px"></td>
                    <td align="center" valign="middle">
                        <input id="btnSubmit" class="button" type="submit" value="submit" />
					</td>
                </tr>
            </table>
        </form>
	</div>
{% endblock %}

{% block script_media %}

    <script type="text/javascript">
        $( document ).ready(function() {
            var messageValue = '{{ message }}';
            if (messageValue != '') {
                $('#message').css('display', 'block');
            }
        });

        $("#btnSubmit").click(function() {
            $(".error").hide();
            var isError = false;
            var newPasswd = $("#txtNewPswd").val();
            var confirmPasswd = $("#txtConfirmPswd").val();
            $("#requiredNewPass").text('');
            $("#requiredConfirmPass").text('');
            if (newPasswd == '') {
                $("#requiredNewPass").text('Please enter the new password.');
                isError = true;
            } else if (newPasswd.length < 6) {
                $("#requiredNewPass").text('Enter minimum 6 characters.');
                isError = true;
            } else if (confirmPasswd == '') {
                $("#requiredConfirmPass").text('Please re-enter your new password.');
                isError = true;
            } else if (newPasswd != confirmPasswd ) {
                $("#requiredConfirmPass").text('Passwords do not match.');
                isError = true;
            }

            if (isError) {
                $(".error").show();
                return false;
            } else {
                return true;
            }
        });

    </script>

{% endblock %}

templates/chartview.html
{% load nvd3_tags %}
{% block load_nvd3_chart_jscss %}
	 {% include_chart_jscss %}
	 {% load_chart chart.charttype chart.chartdata chart.chartcontainer chart.extra %}
{% endblock %}
{% include_container chart.chartcontainer chart.height chart.width %}

templates/linechart.html
{% extends "base.html" %}
{% load nvd3_tags %}

{% block load_nvd3_chart_jscss %}
    {% include_chart_jscss %}
    {% load_chart charttype chartdata chartcontainer extra %}
{% endblock %}

{% block content %}
    {% include_container chartcontainer %}
{% endblock %}

templates/reportdetails.html
{% extends "base.html" %}
{% load media_tags %}

{% block css_media %}
	<link rel="stylesheet" href='{% media_path "css/wizard.css" %}' />
{% endblock %}

{% block side_menu %}
	<ul class="Sidebar-Navi-Descrpition">
		<li class="Active">
			<a href="{% virtual_path %}/accounts/userreportslist/" title="Reports">
				<span class="Circle color-lightblue"></span>
				<span class="Hide-Collapse">Reports</span>
			</a>
		</li>
		<li>
			<a href="#" title="Profile">
				<span class="Circle color-red"></span>
				<span class="Hide-Collapse">Profile</span>
			</a>
		</li>
		<li>
			<a href="#" title="Change Password">
				<span class="Circle color-orange"></span>
				<span class="Hide-Collapse">Change Password</span>
			</a>
		</li>
		<li>
			<a href="#" title="Recent Status">
				<span class="Circle color-lightgreen"></span>
				<span class="Hide-Collapse">Recent Status</span>
			</a>
		</li>
		<li>
			<a href="#" title="Logout">
				<span class="Circle color-green"></span>
				<span class="Hide-Collapse">Logout</span>
			</a>
		</li>
	</ul>
{% endblock %}

{% block content %}
	<h1 id="rdlTitle" class="h1" style="margin-bottom: 0px;">{{ page_title }}</h1>
	<input id="hdndata" type="hidden" value= '{{data}}' />
	<div id="msg">
		<span></span>
	</div>
	<section id="rptCreate">
		<form id="frmReport" action="." method="POST">{% csrf_token %}
			<div id="wizard-2">
				<h3>Choose Datasource</h3>
				<section>
					<div class="widget-block nR">
	                    <div class="grey-box">
	                        <h4 class="grey-tile" title="Data Source">
	                            <div class="min-max minimize" id="datasource-button">
	                            </div>
	                            <b> :: {{ form.datasource.label }} </b>
	                        </h4>
	                        <div id="datasource-expand" style="display: block;">
	                            <div id="dataSource" style="padding:5px">
	                                <div id="datasourceList" style="width: 100%">
                                        {% for datasource in datasources %}
                                            <input type="radio" style="display: unset;" name="datasource" value="{{ datasource.id }}" onchange="loadDimensionsAndMetrics()" /> {{ datasource.name }} <br />
                                        {% endfor %}
                                    </div>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	                <div class="widget-block fL">
	                    <div class="grey-box">
	                        <h4 class="grey-tile" title="Dimensions">
	                            <div class="min-max minimize" id="dimensions-button">
	                            </div>
	                            <b> :: Dimensions</b>
	                        </h4>
	                        <div id="dimensions-expand" style="display: block;">
	                            <div id="dimensions" style="padding:5px">
									<div id="dimensionsList"> </div>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	                <div class="widget-block fR">
	                    <div class="grey-box">
	                        <h4 class="grey-tile" title="Metrics">
	                            <div class="min-max minimize" id="metrics-button">
	                            </div>
	                            <b> :: Metrics</b>
	                        </h4>
	                        <div id="metrics-expand" style="display: block">
	                            <div id="metrics" style="padding:5px">
	                                <div id="metricsList"> </div>
	                            </div>
	                        </div>
	                    </div>
	                </div>						
				</section>

				<h3>Profile</h3>
				<section>
					<div class="Forms-Group">
			            <label class="Label">{{ form.name.label }} <sup class="Mandatory">*</sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.name }}
							<span class="help-block Error_Message" style="display: none;">Please enter the report name</span>
                    	</div>
					</div>
					<div class="Forms-Group">
			            <label class="Label">{{ form.description.label }}</label>
			            <div class="Form_TextBox_Group">
							{{ form.description }}
                    	</div>
					</div>
					<div class="Forms-Group">
			            <label class="Label">{{ form.chart_type.label }}<sup class="Mandatory">*</sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.chart_type }}
							<span class="help-block Error_Message" style="display: none;">Please select chart type</span>
                    	</div>
					</div>
					<div class="Forms-Group">
			            <label class="Label">{{ form.height.label }}<sup class="Mandatory">*</sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.height }}
							<span class="help-block Error_Message" style="display: none;">Please enter chart height</span>
                    	</div>
					</div>
					<div class="Forms-Group">
			            <label class="Label">{{ form.width.label }}<sup class="Mandatory">*</sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.width }}
							<span class="help-block Error_Message" style="display: none;">Please enter chart width</span>
                    	</div>
					</div>
					<div class="Forms-Group">
			            <label class="Label">{{ form.is_chart.label }}<sup class="Mandatory"></sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.is_chart }}
                    	</div>
					</div>
					<div class="Forms-Group">
			            <label class="Label">{{ form.is_tabular.label }}<sup class="Mandatory"></sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.is_tabular }}
                    	</div>
					</div>
					<div class="Forms-Group">
			            <label class="Label">{{ form.is_filter.label }}<sup class="Mandatory"></sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.is_filter }}
                    	</div>
					</div>
					<div class="Forms-Group" id="filter_column">
			            <label class="Label">{{ form.filter_column.label }}<sup class="Mandatory"></sup></label>
			            <div class="Form_TextBox_Group">
							{{ form.filter_column }}
                    	</div>
					</div>
					<div class="Forms-Group">
			            <div class="Form_TextBox_Group">
							<input id="btnSubmit" class="button" type="button" value="submit" style="display:none" />			
                    	</div>
					</div>
				</section>
			</div>
		</form>
	</section>
{% endblock %}

{% block script_media %}
	<script type="text/javascript" src="/media/js/jquery.steps.min.js"></script>
	<script type="text/javascript">

		$( document ).ready(function() {
			$('#filter_column').css('display', 'none');

			$("#wizard-2").steps({
                headerTag: "h3",
                bodyTag: "section",
                transitionEffect: "slideLeft",
				autoFocus: true,
				onStepChanging: function (event, currentIndex, newIndex) {
					var ddlXaxis = ddlYaxis = false;
					$('#msg span').empty();
                    if (currentIndex == 0) {
						$("input:radio[name=ddlXAxis]:checked").each(function() {
                            ddlXaxis = true;
                        });

						$("input:radio[name=ddlYAxis]:checked").each(function() {
                            ddlYaxis = true;
                        });

						if (!ddlXaxis) {
							$('#msg span').append('<p>Please select any dimensions</p>');
						}
                        if (!ddlYaxis) {
							$('#msg span').append('<p>Please select any metrics</p>');
						}
						if (ddlYaxis || ddlXaxis) {
							return false;
						} else {
							$('#msg span').empty();
							return true;
						}
                    }
                },
				onFinishing: function(event, currentIndex) {
					$('#msg span').empty();
					var returnValue = true;
                    if (currentIndex == 1) {
                        if ($('#id_name').val() == '') {
							$('#msg span').append('<p>Please enter the Report Name</p>');
							returnValue = false;
						}
                        if ($('#id_height').val() == '') {
							$('#msg span').append('<p>Please enter the height</p>');
							returnValue = false;
						}
                        if ($('#id_width').val() == '') {
							$('#msg span').append('<p>Please enter the width</p>');
							returnValue = false;
						}
						return returnValue;
                    }
                },
                onFinished: function (event, currentIndex) {
                    $( "#frmReport" ).submit();
                }
            });

			var datasourceId = "{{ datasourceId }}";
			if (datasourceId != '') { 
				$("input[name=datasource][value=" + datasourceId + "]").attr('checked', 'checked');
			} else { 
				$("input[name=datasource][value=" + $("input[name=datasource]").val() + "]").attr('checked', 'checked');
			}
			loadDimensionsAndMetrics();
		});

		function loadDimensionsAndMetrics() {
			var datasource = document.getElementsByName("datasource");
			var data = '';
			if ($('#hdndata').val() != '') {
				data = jQuery.parseJSON(unescape($('#hdndata').val()));
			}
			for (var elem in datasource) {
                if (datasource[elem].checked) {
					$.ajax({
						url: $('#hdnvirtualpath').val() + "/getDimensionsAndMetrics/"+datasource[elem].value,
						cache: false,
						async: false,
						type : "GET",
						dataType: "json",
						success: function(response) { 
							$("#metricsList").empty();
				            $("#dimensionsList").empty();

							var strMetrics = '', strDimensions = '';
							for (var i = 0; i < response.metrics.length; i++) {	
								strMetrics +=  "<input type='checkbox' name='ddlYAxis' value='"+ response.metrics[i]['id'] + "'>"+ response.metrics[i]['name'] + "</input> <br />";						
							}

							for (var i = 0; i < response.dimensions.length; i++) {
								strDimensions +=  "<input type='checkbox' name='ddlXAxis' value='"+ response.dimensions[i]['id'] + "'>"+ response.dimensions[i]['name'] + "</input> <br />";
							}

							$('#dimensionsList').append(strDimensions);
							$('#metricsList').append(strMetrics);
							if (data != '') {
								for (var j = 0; j < data.dimensions.length; j++) {
									$('input[name=ddlXAxis][value="'+ data.dimensions[j]['id'] + '"]').attr('checked', 'checked');
								}

								for (var k = 0; k < data.metrics.length; k++) {
									$('input[name=ddlYAxis][value="'+ data.metrics[k]['id'] + '"]').attr('checked', 'checked');
								}
							}
						}
					});
				}
			}
		}

		$('#id_is_filter').change(function() {
			alert("asdadadadada");
		});

		$('#id_is_filter').click(function() {
			alert("asdadadadada");
		});

	</script>
{% endblock %}

templates/settings.html
{% extends "base.html" %}
{% load media_tags %}

{% block side_menu %}
	<ul class="Sidebar-Navi-Descrpition">
		<li>
			<a href="{% virtual_path %}/accounts/userreportslist/" title="Reports">
				<span class="Circle color-lightblue"></span>
				<span class="Hide-Collapse">Reports</span>
			</a>
		</li>
		<li>
			<a href="#" title="Profile">
				<span class="Circle color-red"></span>
				<span class="Hide-Collapse">Profile</span>
			</a>
		</li>
		<li>
			<a href="{% virtual_path %}/accounts/changepassword/" title="Change Password">
				<span class="Circle color-orange"></span>
				<span class="Hide-Collapse">Change Password</span>
			</a>
		</li>
		<li>
			<a href="#" title="Recent Status">
				<span class="Circle color-lightgreen"></span>
				<span class="Hide-Collapse">Recent Status</span>
			</a>
		</li>
		<li>
			<a href="{% virtual_path %}/accounts/logout/" title="Logout">
				<span class="Circle color-green"></span>
				<span class="Hide-Collapse">Logout</span>
			</a>
		</li>
	</ul>
{% endblock %}

{% block content %}

{% endblock %}

templates/tabularhome.html
{% extends 'home.html' %}
{% load media_tags %} 

{% block side_menu %}
	<ul class="Sidebar-Navi-Descrpition">
		{% for source in datasource %}
		<li>
			<a href="{% virtual_path %}/exploredata/{{source.pk}}" title="Text menu">
				<span class="Circle color-lightgreen"></span>
				<span class="Hide-Collapse">{{source.name}}</span>
			</a>
			<div class="Accordian_Content">
				<ul class="Legend_List">
					<li>
						<h4 class="Legend_List_Title">Dimension</h4>
						<ul class="Legend_SubList">
							{% for field in fields %}
								{% if field.type == 'DIM' %}
									<li>{{field.field}}</li>
								{% endif %}
							{% endfor %}
						</ul>
					</li>
					<li>
						<h4 class="Legend_List_Title">Metrics</h4>
						<ul class="Legend_SubList">
						{% for field in fields %}
							{% if field.type == 'MET'%}
								<li>{{field.field}}</li>
							{% endif %}
						{% endfor %}
						</ul>
					</li>
				</ul>
			</div>
		</li>
		{% endfor %}
	</ul>
{% endblock %}

{% block content %}
	<h1 id="rdlTitle" class="h1">{{ report_info.name }}</h1>	
	<input id="hdntitle" type="hidden" value='{% media_path "" %}{{ report_info.name }}'/>
	<input id="hdnfields" type="hidden" value='{{ colmndef }}'/>
	<input id="hdnpk" type="hidden" value='{{ sourceid }}'/>
	<input id="hdnstartdt" type="hidden" value='{{ fromdate }}'/>
	<input id="hdnenddt" type="hidden" value='{{ todate }}'/>
	<input id="hdnvirtualpath" type="hidden" value='{% virtual_path %}' />
	<div id="widget_container" class="widget-block nR">	
	 	{% include "tableview.html" %}
	</div>
{% endblock %}